[template]
src = "nginx.conf.tmpl"
dest = "/etc/nginx/nginx.conf"
keys = [
  "/preview/fqdn",
  "/primary/live/fqdn",
  "/secondary/live/fqdn",
  "/htpasswd/path",
  "/cert/path"
]
owner = "root"
mode = "0644"